window.NIKKEI_COMPANIES = [
  {
    "slug": "ajinomoto",
    "award": "グランプリ",
    "company_name": "味の素株式会社",
    "report_title": "ASV Report 2025 / Integrated Report 2025",
    "report_note": "2025年度版",
    "manga_title": "アミノの力で世界を変える！就活迷子が見つけた「食×健康」最前線",
    "plot_kisho": "就活で「食品業界は商品企画か営業しかない」と思い込み、研究職志望の美咲は視野が狭くなっている。",
    "plot_sho": "会社説明で、味の素がアミノ酸研究を起点に食品だけでなく医療や電子材料にも価値を広げていることを知る。",
    "plot_ten": "ASV経営の考え方に触れ、社会課題を解くこと自体が事業成長につながる設計だと理解し、自分の専門の活かし方が見えてくる。",
    "plot_ketsu": "美咲は「食の会社」ではなく「健康と暮らしを科学で進化させる会社」として味の素を捉え直し、挑戦を決意する。",
    "business_strength_summary": "アミノサイエンスを核に食品・ヘルスケア・電子材料へ広げる多層的な事業基盤と、ASV経営による社会価値と経済価値の同時追求が強み。",
    "work_appeal_summary": "Purpose浸透、well-being、エンゲージメント、ダイバーシティをKPIで追いながら、挑戦しやすい組織づくりを進めている。",
    "column_1": "アミノ酸の知見を核に、食品だけでなく医療や電子材料にも事業を展開しているので、「研究がそのまま社会実装に近い」会社です。",
    "column_2": "ASV経営は「社会課題を解くほど会社も伸びる」という考え方。健康寿命や栄養課題に向き合う仕事の意味が見えやすいのが特徴です。",
    "column_3": "社員のwell-beingやエンゲージメント、女性管理職比率などを数値で追っており、挑戦と成長を後押しする職場づくりにも本気です。",
    "pdf_url": "https://www.ajinomoto.co.jp/company/en/ir/library/annual/main/02/teaserItems1/0/linkList/0/link/ASV_Report_2025_A4_en.pdf",
    "video_id": "EWNL9UEUMnQ",
    "video_title": "味の素株式会社 video",
    "video_url": "https://www.youtube.com/watch?v=EWNL9UEUMnQ"
  },
  {
    "slug": "itochu",
    "award": "グランプリ",
    "company_name": "伊藤忠商事株式会社",
    "report_title": "Integrated Report 2025",
    "report_note": "2025年度版",
    "manga_title": "商社は「つなぐ」だけじゃない！現場で稼ぐ総合商社の真価",
    "plot_kisho": "蓮は商社に興味はあるが、仕事内容が抽象的で、自分が働く姿を想像できずにいる。",
    "plot_sho": "伊藤忠の説明を通じて、強い領域に集中投資し、非資源や生活消費分野で稼ぐ力を育ててきた歴史を知る。",
    "plot_ten": "単なる仲介ではなく、現場に入り込んで事業を磨く“ハンズオン経営”こそが強みだと分かり、商社像が一変する。",
    "plot_ketsu": "蓮は「広く浅く」ではなく「広い領域で本気で価値を出す」働き方に魅力を感じ、第一志望に据える。",
    "business_strength_summary": "強い分野への集中投資、非資源・消費関連での収益力、そして投資後の現場改善まで踏み込むハンズオン経営が競争優位。",
    "work_appeal_summary": "人材戦略を経営の中核に置き、「挑戦できて報われる職場」を目指して人材獲得・対話・配置を進めている。",
    "column_1": "伊藤忠の強みは、投資して終わりではなく、投資先の事業そのものを強くするところ。だから「経営に近い仕事」を若いうちから体感しやすいです。",
    "column_2": "資源価格に頼りすぎず、生活消費・非資源分野で稼ぐ構造を厚くしているので、景気変動への耐性も意識した経営が見えます。",
    "column_3": "人材を経営資本として扱い、挑戦機会や対話、適材適所を重視。成果主義だけではなく、成長機会の設計まで見ているのが就活生には重要です。",
    "pdf_url": "https://www.itochu.co.jp/en/ir/download/__icsFiles/afieldfile/2025/06/18/FIR2025E_1.pdf",
    "video_id": "qWCB-ctHCP4",
    "video_title": "伊藤忠商事株式会社 video",
    "video_url": "https://www.youtube.com/watch?v=qWCB-ctHCP4"
  },
  {
    "slug": "fujitsu",
    "award": "グランプリ",
    "company_name": "富士通株式会社",
    "report_title": "Fujitsu Integrated Report 2025",
    "report_note": "2025年度版",
    "manga_title": "テクノロジーで社会を動かせ！文系学生が挑むDX最前線",
    "plot_kisho": "颯太は「IT企業はエンジニアしか活躍できない」と思い込み、応募をためらっている。",
    "plot_sho": "富士通のUvanceやモダナイゼーション戦略を知り、顧客課題を業界横断で解く仕事があると分かる。",
    "plot_ten": "業界知識、コンサル、技術基盤を掛け合わせることが富士通の競争優位だと理解し、自分にも役割があると気づく。",
    "plot_ketsu": "颯太は「ITを売る会社」ではなく「社会の仕組みを更新する会社」として富士通を見るようになる。",
    "business_strength_summary": "Fujitsu Uvanceを軸に、業界知識・コンサル・技術基盤・モダナイゼーションを統合して社会実装まで担える点が強い。",
    "work_appeal_summary": "人的資本を重要テーマとして捉え、学習、キャリア、well-beingを土台に長期成長を支える設計になっている。",
    "column_1": "富士通の強みは、技術だけではなく「業界を深く知る力」。だから顧客ごとに解くべき課題を具体的に描けます。",
    "column_2": "Uvanceやモダナイゼーションは、古い仕組みを直す仕事と新しい社会をつくる仕事を両方持てるのが面白いポイントです。",
    "column_3": "人的資本やwell-beingを価値創造の基盤として扱っており、学び続ける人が伸びる会社だと読み取れます。",
    "pdf_url": "https://global.fujitsu/-/media/Project/Fujitsu/Fujitsu-HQ/about/integrated-report/2025/integrated-report-2025-en.pdf",
    "video_id": "QBqx7e4mJR8",
    "video_title": "富士通株式会社 video",
    "video_url": "https://www.youtube.com/watch?v=QBqx7e4mJR8"
  },
  {
    "slug": "asahi_kasei",
    "award": "準グランプリ",
    "company_name": "旭化成株式会社",
    "report_title": "Asahi Kasei Report 2025",
    "report_note": "2025年度版",
    "manga_title": "化学メーカーの枠を超えろ！3つの事業がつながる成長方程式",
    "plot_kisho": "真帆は「メーカーは配属先で人生が決まりそう」と感じ、応募を決めきれない。",
    "plot_sho": "旭化成が3つの事業セクターを持ち、事業ポートフォリオを組み替えながら成長してきたことを知る。",
    "plot_ten": "単なる多角化ではなく、異なる事業を持つからこそ景気変動に強く、新規事業の芽もつくりやすい構造だと理解する。",
    "plot_ketsu": "真帆は「一社で複数業界分の経験値を積める」と気づき、長期で成長できる場として魅力を感じる。",
    "business_strength_summary": "マテリアル・住宅・ヘルスケアの3本柱を持つ分散型ポートフォリオと、再編・新規創出を両立する経営が特徴。",
    "work_appeal_summary": "優秀人材の戦略配置、中途や専門人材の活用、幅広い事業間での学びにより、キャリアの選択肢が広い。",
    "column_1": "旭化成の面白さは、化学だけの会社ではないこと。住宅やヘルスケアまであるから、景気や市場の変化に強い構造を作れます。",
    "column_2": "ポートフォリオを見直しながら次の柱を育てる経営なので、「成熟事業を守るだけ」の会社ではありません。",
    "column_3": "事業が多いぶん、人材配置や専門性の掛け合わせが重要。だから若手でも異分野の知見に触れやすい環境が期待できます。",
    "pdf_url": "https://www.asahi-kasei.com/ir/library/asahikasei_report/pdf/16en.pdf",
    "video_id": "8bCJoCwmH6A",
    "video_title": "旭化成株式会社 video",
    "video_url": "https://www.youtube.com/watch?v=8bCJoCwmH6A"
  },
  {
    "slug": "j_front_retailing",
    "award": "準グランプリ",
    "company_name": "J.フロント リテイリング株式会社",
    "report_title": "統合報告書 2025",
    "report_note": "2025年度版",
    "manga_title": "百貨店のその先へ。街のワクワクを設計するリテール変革",
    "plot_kisho": "葵は小売の未来に不安を感じ、EC全盛の時代に店舗企業で働く意味を見失っている。",
    "plot_sho": "J.フロントが百貨店とPARCOの融合で、モノ売りだけでなく街の価値そのものを高めていると知る。",
    "plot_ten": "売場づくり、エリア戦略、コミュニティ活性化がつながっていることを学び、小売の仕事観が更新される。",
    "plot_ketsu": "葵は「店で売る会社」ではなく「都市の熱量を設計する会社」としてJ.フロントを志望する。",
    "business_strength_summary": "百貨店、PARCO、SC・決済・街づくり機能の融合によって、モノ消費を超えた体験価値をつくれるのが強み。",
    "work_appeal_summary": "異なる業態を横断できるため、販売、企画、開発、地域連携などキャリアの幅が広く、創造性を発揮しやすい。",
    "column_1": "J.フロントの強さは、百貨店単体ではなく“融合”にあります。異なるブランドや業態を掛け合わせ、新しい来店理由をつくれる会社です。",
    "column_2": "売上だけでなく、地域のにぎわいや街の魅力まで成果として捉えているので、仕事のスケールが店舗を超えます。",
    "column_3": "接客だけでなく企画、開発、エリアマネジメントまで関われるため、「人と街を動かす仕事」をしたい就活生に刺さります。",
    "pdf_url": "https://www.j-front-retailing.com/ir/library/pdf/annual/2025/J_FRONT_2025_E_single.pdf",
    "video_id": "AV1TW0qjQso",
    "video_title": "J.フロント リテイリング株式会社 video",
    "video_url": "https://www.youtube.com/watch?v=AV1TW0qjQso"
  },
  {
    "slug": "sumitomo_forestry",
    "award": "準グランプリ",
    "company_name": "住友林業株式会社",
    "report_title": "Integrated Report 2025",
    "report_note": "2025年度版",
    "manga_title": "木のチカラで脱炭素へ！森から街までつなぐ仕事",
    "plot_kisho": "悠真は「環境にいい仕事」と「稼げる仕事」は両立しないのではと悩んでいる。",
    "plot_sho": "住友林業の報告書で、森林経営から木材、住宅、再エネまで一気通貫の事業モデルを知る。",
    "plot_ten": "木を使うだけでなく、世界で森林価値を高めながら脱炭素に挑むビジネスだと分かり、環境と経済の両立を実感する。",
    "plot_ketsu": "悠真は「SDGsっぽい会社」ではなく「森を起点に巨大な産業を動かす会社」として住友林業に惹かれる。",
    "business_strength_summary": "森林経営、木材流通、住宅、再エネをつなぐ一気通貫モデルと、国内外ネットワークによるシナジーが大きい。",
    "work_appeal_summary": "建築・営業・グローバル人材など専門性の高いキャリアを築けるうえ、育成投資や働きやすさの指標も開示されている。",
    "column_1": "住友林業は「木を売る会社」ではなく、森を育て、素材を活かし、住まいまでつなぐサプライチェーン全体を持つ会社です。",
    "column_2": "脱炭素の追い風を受けやすく、しかもグローバルで展開しているので、環境課題を大きな事業機会に変えやすい構造があります。",
    "column_3": "建築士やグローバル人材の育成、ワークライフバランス、タレントマネジメントなど、専門性を長く伸ばせる職場設計も魅力です。",
    "pdf_url": "https://sfc.jp/english/ir/library/pdf/ar2025eng.pdf",
    "video_id": "J5e87enevjY",
    "video_title": "住友林業株式会社 video",
    "video_url": "https://www.youtube.com/watch?v=J5e87enevjY"
  },
  {
    "slug": "sekisui_house",
    "award": "準グランプリ",
    "company_name": "積水ハウス株式会社",
    "report_title": "Value Report 2025 / SEKISUI HOUSE REPORT 2025",
    "report_note": "2025年度版",
    "manga_title": "「幸せをつくる家」はどう生まれる？100年時代の暮らしデザイン",
    "plot_kisho": "日菜は住宅業界を調べるうちに、どの会社も同じに見えてしまい、決め手を失っている。",
    "plot_sho": "積水ハウスのレポートで、100年時代の暮らしを見据えた価値づくりと、専門会社による深い技術力を知る。",
    "plot_ten": "社員の自律性、専門性、協働を軸に変革していることを知り、住宅会社のイメージが“人の幸せを設計する会社”へと変わる。",
    "plot_ketsu": "日菜は、家づくりを通じて人生そのものに関わる仕事の奥行きに惹かれ、志望を固める。",
    "business_strength_summary": "住宅を単体商品としてではなく、健康・つながり・学びまで含む暮らしの価値として再設計している点が強い。",
    "work_appeal_summary": "自律的なキャリア形成、女性活躍、表彰制度、well-being基盤づくりなど、人が伸びる仕組みを長期で積み上げている。",
    "column_1": "積水ハウスは「家を建てる会社」ではなく、100年時代の幸せな暮らし方を提案する会社として報告書を作っています。",
    "column_2": "専門会社による深い技術と、グループでの連携を両立させているので、住宅品質だけでなく新しい価値提案まで進めやすいです。",
    "column_3": "自律的なキャリア開発や女性活躍、well-beingの土台づくりが長年の蓄積として出ており、働き方の進化が見えます。",
    "pdf_url": "https://www.sekisuihouse.co.jp/english/company/sustainable/library/2025/ValueReport2025alle.pdf",
    "video_id": "cJwu323OfBU",
    "video_title": "積水ハウス株式会社 video",
    "video_url": "https://www.youtube.com/watch?v=cJwu323OfBU"
  },
  {
    "slug": "takasago",
    "award": "準グランプリ",
    "company_name": "高砂熱学工業株式会社",
    "report_title": "TAKASAGO CORPORATE REPORT 2025",
    "report_note": "2025年度版",
    "manga_title": "空気で未来を変える！見えないインフラに挑む技術者たち",
    "plot_kisho": "蒼は「空調設備」は裏方すぎて、やりがいを感じられるか不安に思っている。",
    "plot_sho": "高砂熱学の報告書で、クリーンルームや省エネ、カーボンニュートラルなど社会の核心を支える技術だと知る。",
    "plot_ten": "空気や熱の制御が半導体、医薬、都市インフラの品質そのものを左右することに気づき、見えない技術の大きさを実感する。",
    "plot_ketsu": "蒼は「裏方」ではなく「社会の土台を設計する主役」だと捉え直し、挑戦を決意する。",
    "business_strength_summary": "空調・環境エンジニアリングを軸に、クリーンルーム、省エネ、脱炭素、DX/BIMまで広げる提案力が強み。",
    "work_appeal_summary": "大規模プロジェクトで専門性を磨きつつ、脱炭素やDXといった時代のど真ん中の課題に向き合える。",
    "column_1": "高砂熱学の強さは、空気や熱という“見えにくい価値”を、品質・省エネ・生産性という形で顧客成果につなげられることです。",
    "column_2": "半導体工場や医薬分野のクリーン環境、都市の脱炭素まで支えるので、景気の流れと社会課題の両方に接続した事業です。",
    "column_3": "設備会社でも、DXやBIM、カーボンニュートラル案件に関われるので、技術者としての市場価値を広げやすい環境と言えます。",
    "pdf_url": "https://www.tte-net.com/sustainability/pdf/cr_2025.pdf",
    "video_id": "dOQe6l9kJMY",
    "video_title": "高砂熱学工業株式会社 video",
    "video_url": "https://www.youtube.com/watch?v=dOQe6l9kJMY"
  },
  {
    "slug": "tokyo_electron",
    "award": "準グランプリ",
    "company_name": "東京エレクトロン株式会社",
    "report_title": "Integrated Report 2025",
    "report_note": "2025年度版",
    "manga_title": "半導体の裏側で世界を動かす！装置メーカーの本気",
    "plot_kisho": "凛は半導体といえばチップ設計の会社ばかり見ており、装置の面白さに気づいていない。",
    "plot_sho": "東京エレクトロンが巨大な installed base と特許群を持ち、半導体製造の進化を根底で支えていると知る。",
    "plot_ten": "R&D投資、サービス体制、人材育成が一体で競争力をつくっていると理解し、「作って終わりではない強さ」に惹かれる。",
    "plot_ketsu": "凛は、世界のテクノロジー競争を裏側から加速させる仕事に魅力を感じ、志望先に加える。",
    "business_strength_summary": "業界最大級の installed base、豊富な特許、積極的な研究開発投資により、半導体製造装置の競争力を磨き続けている。",
    "work_appeal_summary": "TEL UNIVERSITYや育成計画、グローバル採用強化など、専門性を伸ばす仕組みが明確で、学び続ける人に向く。",
    "column_1": "東京エレクトロンは、装置を納めた後のサービスや改善提案まで含めて強い会社。だから顧客との距離が近く、技術が現場でどう効くか見えます。",
    "column_2": "AIや先端パッケージングの伸びで半導体需要が高まるなか、装置メーカーは産業全体のボトルネックを解く存在です。",
    "column_3": "人材育成の仕組みがかなり具体的で、キャリアプランや学習機会を明示している点は、成長志向の就活生に大きな安心材料です。",
    "pdf_url": "https://www.tel.com/ir/library/ar/pjsoh100000000rc-att/ir2025_all_en.pdf",
    "video_id": "5GJ3iz-4i8A",
    "video_title": "東京エレクトロン株式会社 video",
    "video_url": "https://www.youtube.com/watch?v=5GJ3iz-4i8A"
  },
  {
    "slug": "tok",
    "award": "準グランプリ",
    "company_name": "東京応化工業株式会社",
    "report_title": "統合レポート2024",
    "report_note": "2025年公開版（レポート表記は2024）",
    "manga_title": "AI時代の半導体を支える黒子へ。材料メーカーの逆転劇",
    "plot_kisho": "直樹は、半導体業界で材料メーカーがどこまで重要なのかピンと来ていない。",
    "plot_sho": "TOKのレポートで、前工程・後工程の両方に効く材料ポートフォリオと、生成AI向け半導体への対応力を知る。",
    "plot_ten": "材料こそが性能と歩留まりを左右すること、さらにMIや計算化学で開発のスピードも変わることに衝撃を受ける。",
    "plot_ketsu": "直樹は「目立たない素材」ではなく「産業進化を加速させるキープレイヤー」としてTOKを志望する。",
    "business_strength_summary": "前工程・後工程を支えるフォトレジスト群と、生成AI半導体向けの幅広い製品群、MI・計算化学による開発力が強み。",
    "work_appeal_summary": "人的資本の幸福を重視し、安全で働きやすい環境づくりとグローバル人材育成を同時に進めている。",
    "column_1": "TOKは半導体材料の会社ですが、前工程だけでなく後工程まで見ている点が効いています。AI向け需要の広がりを取り込みやすい構造です。",
    "column_2": "材料インフォマティクスや計算化学を使うことで、経験頼みではない開発スピードを目指しているのが今っぽい強みです。",
    "column_3": "人的資本の“幸福”を正面から掲げ、安心して働ける環境やグローバル人材の育成を重視しているのも、研究職志望には魅力です。",
    "pdf_url": "https://www.tok.co.jp/application/files/6817/6585/9760/Integrated_report2024_en_all_a4.pdf",
    "video_id": "UIsvmq01MoI",
    "video_title": "東京応化工業株式会社 video",
    "video_url": "https://www.youtube.com/watch?v=UIsvmq01MoI"
  },
  {
    "slug": "fujifilm_holdings",
    "award": "準グランプリ",
    "company_name": "富士フイルムホールディングス株式会社",
    "report_title": "Integrated Report 2025",
    "report_note": "2025年度版",
    "manga_title": "フィルム会社はなぜ強い？変身し続けるイノベーション企業",
    "plot_kisho": "結衣は富士フイルムに昔のフィルム会社のイメージを持ったまま、志望候補から外していた。",
    "plot_sho": "レポートを読み、ヘルスケア、バイオCDMO、半導体材料、AI活用へと進化した事業ポートフォリオに驚く。",
    "plot_ten": "過去の強みを捨てたのではなく、技術資産を変換して次の成長領域に移してきたことが分かり、会社の見え方が変わる。",
    "plot_ketsu": "結衣は「変化に強い会社」で働くことの価値を感じ、富士フイルムを本格的に研究し始める。",
    "business_strength_summary": "ヘルスケア、バイオCDMO、半導体材料などへ技術資産を転換し、AIやDXも成長ドライバーにしている点が強い。",
    "work_appeal_summary": "サーベイと対話を通じた職場づくり、グローバル人材の活躍、事業横断のイノベーション機会が魅力。",
    "column_1": "富士フイルムのすごさは、“事業転換”を一度きりの改革で終わらせず、技術資産を次の成長分野へ繰り返し移していることです。",
    "column_2": "ヘルスケアや半導体材料、バイオCDMOなど成長市場を複数持つので、景気や技術変化への対応力が高い会社だと読めます。",
    "column_3": "社員の声を拾うサーベイや対話を重視し、ダイナミックな職場環境づくりを進めているため、変化を楽しめる人に向いています。",
    "pdf_url": "https://ir.fujifilm.com/en/investors/ir-materials/integrated-report/main/00/teaserItems1/01/linkList/0/link/fh_2025_alle_a4.pdf",
    "video_id": "Pw869nTf-QI",
    "video_title": "富士フイルムホールディングス株式会社 video",
    "video_url": "https://www.youtube.com/watch?v=Pw869nTf-QI"
  },
  {
    "slug": "mitsui_fudosan",
    "award": "準グランプリ",
    "company_name": "三井不動産株式会社",
    "report_title": "統合報告書 2025",
    "report_note": "2025年度版",
    "manga_title": "街づくりは不動産だけじゃない。体験を設計する総合デベロッパー",
    "plot_kisho": "亮はデベロッパーの仕事を華やかな再開発のイメージでしか捉えられていない。",
    "plot_sho": "三井不動産のレポートで、オフィスや商業だけでなく、物流、ホテル、住まい、DXまで一体で価値をつくる姿を知る。",
    "plot_ten": "不動産を建てるのではなく、体験やサービスまで設計して“街の使われ方”を変えるのが強みだと理解する。",
    "plot_ketsu": "亮は「街のハコを作る会社」ではなく「都市の体験を編集する会社」として三井不動産を志望する。",
    "business_strength_summary": "多様なアセットを持ちながら、& INNOVATION 2030のもとで不動産とサービス、DXを組み合わせる総合力が強い。",
    "work_appeal_summary": "100超の研修プログラム、ジョブローテーション、ダイバーシティ施策など、長期で人を育てる仕組みが見える。",
    "column_1": "三井不動産の強みは、オフィス・商業・住宅・物流・ホテルなど多様な事業を一社で持ち、それらを組み合わせられることです。",
    "column_2": "不動産そのものではなく、そこで生まれる体験やサービスまで価値にしているので、景気変動に対しても打ち手を増やしやすいです。",
    "column_3": "研修やジョブローテーションが厚く、街づくりの中でもいろいろな機能を経験しながらキャリアをつくれる点が魅力です。",
    "pdf_url": "https://www.mitsuifudosan.co.jp/corporate/ir/library/integratedreport/pdf/IR2025_ja.pdf",
    "video_id": "zm9aWASGk5w",
    "video_title": "三井不動産株式会社 video",
    "video_url": "https://www.youtube.com/watch?v=zm9aWASGk5w"
  }
];
